vadim_index:
    pattern:  /index
    defaults: { _controller: VadimGuestBundle:Default:index }


vadim_create:
    pattern:  /create
    defaults: { _controller: VadimGuestBundle:Default:create }

vadim_delete:
     pattern:  /delete/{slug}
     defaults: { _controller: VadimGuestBundle:Default:delete }

vadim_see:
     pattern:  /see/{slug}
     defaults: { _controller: VadimGuestBundle:Default:see }
